export const fakeFeedback = [
  {
    message: "Excellent customer support. The team resolved my issue quickly.",
    sentiment: "POSITIVE",
    status: "NEW",
    theme: "Support",
    channel: "Email",
  },
  {
    message: "Delivery was delayed by three days.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Delivery",
    channel: "Website",
  },
  {
    message: "The mobile app is easy to use and very responsive.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "UI/UX",
    channel: "Mobile App",
  },
  {
    message: "Checkout process is confusing.",
    sentiment: "NEGATIVE",
    status: "NEW",
    theme: "Checkout",
    channel: "Website",
  },
  {
    message: "The product quality exceeded my expectations.",
    sentiment: "POSITIVE",
    status: "NEW",
    theme: "Product",
    channel: "Email",
  },
  {
    message: "Customer service was slow to respond.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Support",
    channel: "Live Chat",
  },
  {
    message: "Loved the new dashboard design.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Dashboard",
    channel: "Mobile App",
  },
  {
    message: "Payment failed multiple times.",
    sentiment: "NEGATIVE",
    status: "NEW",
    theme: "Payment",
    channel: "Website",
  },
  {
    message: "Great experience using the application.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Experience",
    channel: "Google Review",
  },
  {
    message: "Navigation can be improved.",
    sentiment: "NEUTRAL",
    status: "NEW",
    theme: "Navigation",
    channel: "Email",
  },
  {
    message: "The login process is very smooth.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Authentication",
    channel: "Website",
  },
  {
    message: "Notifications are delayed.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Notification",
    channel: "Mobile App",
  },
  {
    message: "Very satisfied with customer support.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Support",
    channel: "Facebook",
  },
  {
    message: "Need dark mode support.",
    sentiment: "NEUTRAL",
    status: "NEW",
    theme: "Appearance",
    channel: "Twitter",
  },
  {
    message: "Reports load much faster now.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Performance",
    channel: "Email",
  },
  {
    message: "Unable to upload CSV file.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "CSV Upload",
    channel: "Website",
  },
  {
    message: "Analytics page looks fantastic.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Analytics",
    channel: "Google Review",
  },
  {
    message: "Need more filter options.",
    sentiment: "NEUTRAL",
    status: "NEW",
    theme: "Filters",
    channel: "Website",
  },
  {
    message: "The feedback dashboard is impressive.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Dashboard",
    channel: "LinkedIn",
  },
  {
    message: "Search feature is slow.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Search",
    channel: "Email",
  },
  {
    message: "Easy registration process.",
    sentiment: "POSITIVE",
    status: "NEW",
    theme: "Registration",
    channel: "Website",
  },
  {
    message: "Profile update worked perfectly.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Profile",
    channel: "Mobile App",
  },
  {
    message: "Export to CSV should be faster.",
    sentiment: "NEUTRAL",
    status: "NEW",
    theme: "Export",
    channel: "Email",
  },
  {
    message: "The application crashes occasionally.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Crash",
    channel: "Play Store",
  },
  {
    message: "Amazing user interface.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "UI",
    channel: "App Store",
  },
  {
    message: "Need multilingual support.",
    sentiment: "NEUTRAL",
    status: "NEW",
    theme: "Language",
    channel: "Facebook",
  },
  {
    message: "Email notifications work perfectly.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "Notification",
    channel: "Email",
  },
  {
    message: "The website loads slowly on mobile.",
    sentiment: "NEGATIVE",
    status: "REVIEW",
    theme: "Performance",
    channel: "Website",
  },
  {
    message: "Customer onboarding is excellent.",
    sentiment: "POSITIVE",
    status: "NEW",
    theme: "Onboarding",
    channel: "LinkedIn",
  },
  {
    message: "Everything works as expected.",
    sentiment: "POSITIVE",
    status: "ACTIONED",
    theme: "General",
    channel: "Email",
  }
];